# Generated by Django 5.0.6 on 2024-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
